### ISSUE TITLE
Error generating JSON fields 

### ISSUE THREAD

**Issue by mebtex** [oscarafdev/migrations-generator#11]
Hi, I have columns in the MySQL database with the JSON data type, but when I start the generation I get migrations where all the JSON fields are specified with the TEXT type.

Say it should be so?

Thanks!
Thanks for adding support for Laravel 6!

**Comment by willsmanley** [comment]
Was about to open a new issue for this same topic.

**Comment by oscarafdev** [comment]
Hello! Sorry for the wait, I have released a new version with the solution to the issue
