### ISSUE TITLE
support for laravel 7 ?

### ISSUE THREAD

**Issue by genesiscz** [oscarafdev/migrations-generator#17]
It would be nice to have a support for laravel 7. Care to update?

**Comment by achatainga** [comment]
Try this, it is working on Laravel 7 and tested... I used it but I am still searching to see if there is a better option out there... Comment if you find
https://github.com/kitloong/laravel-migrations-generator

**Comment by oscarafdev** [comment]
`composer require oscarafdev/migrations-generator 2.0.18`
