### ISSUE TITLE
Laravel 7 Added but still composer.json file still has reference to laravel 6 

### ISSUE THREAD

**Issue by envatic** [oscarafdev/migrations-generator#20]
Cant Install on Laravel 7
` composer require oscarafdev/migrations-generator  2.0.17`
`./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oscarafdev/migrations-generator v2.0.17 requires oscarafdev/laravel-4-generators ~3.1.4 -> satisfiable by oscarafdev/laravel-4-generators[3.1.4].
    - Installation request for oscarafdev/migrations-generator 2.0.17 -> satisfiable by oscarafdev/migrations-generator[v2.0.17].
    - Conclusion: remove laravel/framework v7.3.0
    - Conclusion: don't install laravel/framework v7.3.0
    - oscarafdev/laravel-4-generators 3.1.4 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0], laravel/framework[6.x-dev].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.3.0
    - Can only install one of: laravel/framework[6.x-dev, v7.3.0].
    - Installation request for laravel/framework (locked at v7.3.0, required as ^7.0) -> satisfiable by laravel/framework[v7.3.0].

Installation failed, reverting ./composer.json to its original content.`

**Comment by AntiPaste** [comment]
+1, the PR I created to add Laravel 7 support (https://github.com/oscarafdev/migrations-generator/pull/19) mentioned that another PR (https://github.com/oscarafdev/Laravel-4-Generators/pull/1) needs to be merged as well for full support of Laravel 7, but I guess it was overlooked.

@oscarafdev Can you merge the other PR as well?

**Comment by mruz** [comment]
@oscarafdev and release a new tag

**Comment by oscarafdev** [comment]
`composer require oscarafdev/migrations-generator 2.0.18`
