### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by michabbb** [oscarafdev/migrations-generator#23]
```
Deprecation Notice: Class Way\Generators\Templates\Data\Controller located in ./vendor/oscarafdev/laravel-4-generators/src/Way/Generators/templates/Data/Controller.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Way\Generators\Templates\Data\Migration located in ./vendor/oscarafdev/laravel-4-generators/src/Way/Generators/templates/Data/Migration.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```
`Composer version 1.10.4`
`PHP 7.4.4`
`laravel/framework                    v7.11.0`

**Comment by webdantas** [comment]
I have this same error. AND another:
Problem 1
    - The requested package way/generators dev-feature/laravel-five-stable exists as way/generators[1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.6.1, 3.0.1, 3.0.2, 3.0.3, dev-master, dev-rewrite, 3] but these are rejected by your constraint.

 Problem 2
    - Installation request for xethron/migrations-generator dev-l5 -> satisfiable by xethron/migrations-generator[dev-l5].
    - Conclusion: remove laravel/framework v7.11.0
    - Conclusion: don't install laravel/framework v7.11.0
    - xethron/migrations-generator dev-l5 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].

**Comment by oscarafdev** [comment]
> ```
> Deprecation Notice: Class Way\Generators\Templates\Data\Controller located in ./vendor/oscarafdev/laravel-4-generators/src/Way/Generators/templates/Data/Controller.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> Deprecation Notice: Class Way\Generators\Templates\Data\Migration located in ./vendor/oscarafdev/laravel-4-generators/src/Way/Generators/templates/Data/Migration.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> ```
> 
> `Composer version 1.10.4`
> `PHP 7.4.4`
> `laravel/framework v7.11.0`

Try updating the composer version

**Comment by oscarafdev** [comment]
> I have this same error. AND another:
> Problem 1
> - The requested package way/generators dev-feature/laravel-five-stable exists as way/generators[1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.6.1, 3.0.1, 3.0.2, 3.0.3, dev-master, dev-rewrite, 3] but these are rejected by your constraint.
> 
> Problem 2
> - Installation request for xethron/migrations-generator dev-l5 -> satisfiable by xethron/migrations-generator[dev-l5].
> - Conclusion: remove laravel/framework v7.11.0
> - Conclusion: don't install laravel/framework v7.11.0
> - xethron/migrations-generator dev-l5 requires xethron/laravel-4-generators ~3.1.0 -> satisfiable by xethron/laravel-4-generators[3.1.0, 3.1.1].

You are installing the wrong package. "xethron / migrations-generator" is not this package, use "composer require oscarafdev/migrations-generator 2.0.19"

**Comment by webdantas** [comment]
Look, I checked that there is still an error, which command to run ?:

Command "migrate:generate" is not defined.  
                                              
  Did you mean one of these?                  
      event:generate                          
      key:generate                            
      migrate                                 
      migrate:fresh                           
      migrate:install                         
      migrate:refresh                         
      migrate:reset                           
      migrate:rollback                        
      migrate:status

**Comment by michabbb** [comment]
@oscarafdev in which way do you think, updating composer will change anything, if composer itself says: 

> what you are doing - right now - will not work in newer version of composer

i don´t get it 😄

**Comment by oscarafdev** [comment]
Fixed.
