### ISSUE TITLE
Undefined property: stdClass::$column_name

### ISSUE THREAD

**Issue by acushlakoncept** [oscarafdev/migrations-generator#25]
I get this error on tables with enums:

Undefined property: stdClass::$column_name at /Users/apple/Desktop/HMS/vendor/xethron/migrations-generator/src/Xethron/MigrationsGenerator/Generators/FieldGenerator.php:76)"} []

**Comment by ricyoca** [comment]
Is there any progress in this issue? I've been experiencing the very same bug

**Comment by acushlakoncept** [comment]
Nothing yet

**Comment by victor-elceaninov** [comment]
as a temporary solution
`vendor/oscarafdev/migrations-generator/src/OscarAFDev/MigrationsGenerator/Generators/FieldGenerator.php - line 73`
```php
        protected function setEnum(array $fields, $table)
	{
		foreach ($this->getEnum($table) as $column) {
			$fields[$column->COLUMN_NAME]['type'] = 'enum';
			$fields[$column->COLUMN_NAME]['args'] = str_replace('enum(', 'array(', $column->COLUMN_TYPE);
		}
		return $fields;
	}
```

**Comment by kossa** [comment]
@victor-elceaninov  It works for me, why temporary ?

**Comment by leighlatham123** [comment]
> as a temporary solution
> `vendor/oscarafdev/migrations-generator/src/OscarAFDev/MigrationsGenerator/Generators/FieldGenerator.php - line 73`
> 
> ```
>         protected function setEnum(array $fields, $table)
> 	{
> 		foreach ($this->getEnum($table) as $column) {
> 			$fields[$column->COLUMN_NAME]['type'] = 'enum';
> 			$fields[$column->COLUMN_NAME]['args'] = str_replace('enum(', 'array(', $column->COLUMN_TYPE);
> 		}
> 		return $fields;
> 	}
> ```

Can confirm this works, thanks.

**Comment by oscarafdev** [comment]
Thank you for reporting the bug, I apologize for taking so long to fix it. I have already worked on the solution and you will be able to see it in the new version that I will release in a few moments.
