### ISSUE TITLE
Recommended Installation

### ISSUE THREAD

**Issue by jasperf** [oscarafdev/migrations-generator#26]
Should the recommended installation way not be 
```
composer require oscarafdev/migrations-generator --dev
``` 
instead of 
```
composer require oscarafdev/migrations-generator
```
? You really only use it for development purposes to get the migrations based on the existing database tables after all..

Also perhaps README.md could also use example like

```
php artisan migrate:generate --path=database/migrations/backup --connection="mysql_backup"
```

with connection and path used.

**Comment by oscarafdev** [comment]
The truth is I have neglected this package, I worked on a new version, probably write it from 0 and include a wiki.

PD: ty!
