### ISSUE TITLE
use Illuminate\Support\Facades\Schema in Laravel 7

### ISSUE THREAD

**Issue by ulisesprieto** [oscarafdev/migrations-generator#28]
The migrate:generate works exceptional, but everytime I have to include the Facades\Schema for every table.
I'm using Laravel 7
![image](https://user-images.githubusercontent.com/44220656/88526046-0e133900-cfc1-11ea-85ea-72de3ef7608a.png)

**Comment by oscarafdev** [comment]
Thank you for reporting the bug, I apologize for taking so long to fix it. I have already worked on the solution and you will be able to see it in the new version that I will release in a few moments.
