### ISSUE TITLE
Exception when processing columns of type ENUM

### ISSUE THREAD

**Issue by sburkett** [oscarafdev/migrations-generator#3]
When retrieving information about the columns assigned to a table, the resulting column names should be in upper case, not lower. It was throwing an exception with the lower case ones. I believe this only affected columns with type `ENUM`. I've created a PR for a fix: #2

**Comment by sburkett** [comment]
I should add that this is under Laravel 6.x and MySQL 8.x

**Comment by oscarafdev** [comment]
Hi, thanks for reporting the error and for fixing it!
