### ISSUE TITLE
timestamp precisions  not supported

### ISSUE THREAD

**Issue by wvdongen** [oscarafdev/migrations-generator#30]
In a Laravel migration it is possible to set the timestamp precision for microseconds:

```php
$table->timestamps(6);
```

Example SQL:

```sql
create table dummy
(
    created_at        timestamp(6)     null,
    updated_at        timestamp(6)     null,
);
```

currently, the field generator doesn't look at the precision (length) and only generates `$table->timestamps()`, which is incorrect.

**Comment by oscarafdev** [comment]
I will try to release a version this weekend. ty

**Comment by gander** [comment]
**Laravel 6.x**:
```
Syntax error or access violation: 1426 Too-big precision 10 specified for 'created_at'. Maximum is 6.
```
