### ISSUE TITLE
Error cuando se genera un campo tipo string

### ISSUE THREAD

**Issue by GlowerTvg** [oscarafdev/migrations-generator#31]
(google traslator):

When a migration is generated from the database to the laravel migrations folder, the string fields are generated incorrectly by placing two single quotes at the beginning and at the end.

Error image:
https://i.imgur.com/uLDHtUJ.png

-------------------

(original):

Cuando se genera una migración desde la base de datos a la carpeta de migraciones de laravel, los campos tipo string se generan de forma incorrecta colocando dos comillas simples al inicio y al final.

Imagen del error:
https://i.imgur.com/uLDHtUJ.png

**Comment by ed-iv** [comment]
Same issue here, looks like same issue as #32 where extra quotes are being added to array argument for index.

**Comment by oscarafdev** [comment]
Hola @GlowerTvg , gracias por reportar el error, será solucionado cuanto antes, mientras tanto podes usar la versión anterior.
