### ISSUE TITLE
Unique index syntax error 

### ISSUE THREAD

**Issue by genesiscz** [oscarafdev/migrations-generator#32]
I have unique index of 2 keys and i get this row

`			$table->unique('['export_id','shop_order_id']', 'export_id_shop_order_id');`
latest version.

**Comment by oscarafdev** [comment]
Thanks for reporting the bug, between today and tomorrow I will release an update with the corresponding fixes. Regards!

**Comment by genesiscz** [comment]
Oh and json field is probably not working properly, too, but it's already as an issue there https://github.com/oscarafdev/migrations-generator/issues/11

**Comment by oscarafdev** [comment]
Hello! Sorry for the wait, I have released a new version with the solution to the issue
