### ISSUE TITLE
Double Single Quotes in Generated Migration

### ISSUE THREAD

**Issue by c-myers1** [oscarafdev/migrations-generator#34]
Hi, I just tried this and I have single quotes duplicated around all auto-increment fields and randomly on others. An example from one of the tables below.

not sure how to troubleshoot this. 
  
        public function up()
        {		
            Schema::create('customer_orders_sm', function(Blueprint $table)
		{
			$table->integer(''id'', true);                   // repeated single-quotes
			$table->string(''ordercode'', 20)->nullable();   // repeated single-quotes
			$table->integer('OrgID')->nullable();
			$table->integer('csmid')->nullable()->index('csmid');
    // etc.

Strangely In the "add_foreign_keys..." migrations, everything is fine.

**Comment by eyounelson** [comment]
I'm having the same issues.

@c-myers1 are you also using MYSQL 8?

**Comment by c-myers1** [comment]
> I'm having the same issues.
> 
> @c-myers1 are you also using MYSQL 8?

Not at all. Humble ol' 5.6.

**Comment by weileong17** [comment]
I am having the same issue as well.

**Comment by alexdpunkt** [comment]
Indeed, that problem exists. 

```
	Schema::create('action_events', function(Blueprint $table) {
		$table->bigInteger(''id'', true)->unsigned();
		$table->char(''batch_id'', 36);
		$table->integer('user_id')->unsigned()->index();
		$table->string('name');
		$table->string('actionable_type');
		$table->integer('actionable_id')->unsigned();
		$table->string('target_type');
		$table->integer('target_id')->unsigned();
		$table->string('model_type');
		$table->integer('model_id')->unsigned()->nullable();
		$table->text('fields');
		$table->string(''status'', 25)->default('running');
		$table->text('exception');
		$table->timestamps(10);
		$table->text('original')->nullable();
		$table->text('changes')->nullable();
		$table->index(['actionable_type','actionable_id']);
		$table->index(['batch_id','model_type','model_id']);
	});
```

**Comment by remmelt** [comment]
```gsed -Ei 's/''''([a-zA-Z0-9_]+)''''/''\1''/g' database/migrations/*.php```

**Comment by siaoynli** [comment]
https://github.com/siaoynli/laravel-migrations-generator  

i fixed  @alexdpunkt   @c-myers1

**Comment by siaoynli** [comment]
you can use the package here : https://github.com/kitloong/laravel-migrations-generator

**Comment by oscarafdev** [comment]
Hello! Sorry for the wait, I have released a new version with the solution to the issue

**Comment by oscarafdev** [comment]
Hello! Sorry for the wait, I have released a new version with the solution to the issue
