### ISSUE TITLE
Unknown database type point requested

### ISSUE THREAD

**Issue by Anisi** [oscarafdev/migrations-generator#4]
```
Doctrine\DBAL\DBALException  : Unknown database type point requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.
```

**Comment by oscarafdev** [comment]
In your migration, add the following function:

`public function __construct()
{
    \Illuminate\Support\Facades\DB::getDoctrineSchemaManager()
       ->getDatabasePlatform()->registerDoctrineTypeMapping('point', 'string');
}`
