### ISSUE TITLE
Foreign keys in the same migration as tables

### ISSUE THREAD

**Issue by mruz** [oscarafdev/migrations-generator#7]
Could we change this? 
> Laravel Migrations Generator will first generate all the tables, columns and indexes, and afterwards setup all the foreign key constraints

In the drop() we could drop the foreign keys first and then drop table.

**Comment by Putr** [comment]
This can be a problem if your tables are not generated in the correct order (i.e. you're trying to create a constraint for a table that has not been created yet). This would force the generator to "figure out" the correct order which just complicates everything.

Best just to do it after.

**Comment by oscarafdev** [comment]
> This can be a problem if your tables are not generated in the correct order (i.e. you're trying to create a constraint for a table that has not been created yet). This would force the generator to "figure out" the correct order which just complicates everything.
> 
> Best just to do it after.

I share your opinion, anyway I will think of a solution.
