### ISSUE TITLE
Undefined property stdClass::$COLUMN_TYPE

### ISSUE THREAD

**Issue by genesiscz** [oscarafdev/migrations-generator#9]
Hello,

using latest laravel (6.15).

Simple artistan migrate:generate throw an ErrorException: Undefined property stdClass::$COLUMN type  [here](https://github.com/oscarafdev/migrations-generator/blob/master/src/OscarAFDev/MigrationsGenerator/Generators/FieldGenerator.php#L76) 

but you are getting it lower case [here](https://github.com/oscarafdev/migrations-generator/blob/master/src/OscarAFDev/MigrationsGenerator/Generators/FieldGenerator.php#L58).

Simply replacing it with lowercase helped. I am aware of [this issue](https://github.com/oscarafdev/migrations-generator/issues/6) but it probably broke somehow else

**Comment by oscarafdev** [comment]
I will investigate, thanks

**Comment by sbine** [comment]
Can confirm: I got the same error and replacing `COLUMN_NAME` with `column_name` and `COLUMN_TYPE` with `column_type` fixed it.
